name: Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          repository: Patrick-Venturini/ebac-hub-de-leitura-integrado
          path: app

      - name: Instalando dependencias do app
        working-directory: app
        run: npm install

      - name: Subindo a aplicação local
        working-directory: app
        run: npm start &

      - name: Aguardar aplicação
        run: npx wait-on http://localhost:3000

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Instalar dependencias
        run: npm install

      - name: Executar testes
        run: npm test
        continue-on-error: true

      - name: Gerar relatorio
        run: npm run report:generate

      - name: Publicar relatório no GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
